### ISSUE TITLE
Setup Confusion

### ISSUE THREAD

**Issue by benjaminlill** [AydinHassan/magento-extension-base#6]
The exception message you received when you enter an incorrect project name could be confusing. Instead of outputting 'Project name should be lowercase, slash separated e.g. jhhello/social' I would output something relating to your module name, for example 'Project name should be lowercase, slash separated e.g. If module name is JhHello_SocialModule input jh-hello/social-module'. This also takes into account any camel casing.

**Comment by AydinHassan** [comment]
Fixed in 630573b1259
